language: generic
dist: trusty
install:
  - sudo apt-get --yes install libxml2-utils
script:
  - cat /etc/issue
  - cat /proc/version
  - cat /etc/*release*
  - chmod +x ./checker.sh
  - chmod +x ./deploy.sh
  - chmod +x ./combine.sh
  - ./checker.sh
  - ./combine.sh
  - ./deploy.sh > /dev/null
